### ISSUE TITLE
Annoying exception on server start (Denizen)

### ISSUE THREAD

**Issue by Namnodorel** [egold555/CorpseReborn#2]
Hey,

when I start up my (1.10.2) server, every time this exception pops up:

http://pastebin.com/BduXjD0Y

As far as I can see everything is still working, but it is really annoying to have it in the console after every restart at best, and disables an important feature at worst.

**Comment by egold555** [comment]
Hmm. What version of spigot are you running? Also could you send me a list of your plugins? (Screenshots are fine)

**Comment by Namnodorel** [comment]
Actually, many... I'm gonna try to figure out if the error is caused by any specific plugin

**Comment by egold555** [comment]
The error is caused by my plugin. Either because your server version doesn't have channels or some other plugin is doing funky things with all the server channels. I can do some testing. Do /ver and send me a screenshot and I can see if it's a plugin or a server issue :)
Also make sure your using the most up to date version of spigot 1.10.2 and my plugin
Thanks,

-Eric

"If life gives you lemons make lemonade. If life gives you melons you might be dyslexic"

On Nov 23, 2016, at 11:55 AM, Namnodorel <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, many... I'm gonna try to figure out if the error is caused by any specific plugin

-

**Comment by Namnodorel** [comment]
It appears to occur with Denizen, especially the 1.10 build https://dev.bukkit.org/bukkit-plugins/denizen/files/34-denizen-1-0-0r2-mc-1-10-1-9-4-1-8-8/

I have the latest version of Spigot 1.10.2 and CorpseReborn is up-to-date

**Comment by egold555** [comment]
Hm. I'll take a look when I get home.

Thanks,

-Eric

"If life gives you lemons make lemonade. If life gives you melons you might be dyslexic"

On Nov 23, 2016, at 12:01 PM, Namnodorel <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears to occur with Denizen, especially the 1.10 build https://dev.bukkit.org/bukkit-plugins/denizen/files/34-denizen-1-0-0r2-mc-1-10-1-9-4-1-8-8/

I have the latest version of Spigot 1.10.2 and CorpseReborn is up-to-date

-

**Comment by egold555** [comment]
It does seem to be a conflicting problem with Denizen. This is very strange
