### ISSUE TITLE
(enhancement) No corpse if inventory is empty

### ISSUE THREAD

**Issue by arturek1666** [egold555/CorpseReborn#66]
Hi, can you add so if player dies without any items in inventory the corpse will not spawn?. As for my server there is no point of the corpse to spawn if player has nothing in inventory

**Comment by smmmadden** [comment]
I like the option myself to spawn a corpse when no inventory is present.  It just means it can't be looted but eventually would despawn.  You can change the config file to do what you need.
`
#Enable checking for new versions of the plugin?
enable-update-checker: true

#Time in seconds until the corpse despawns. Set to -1 for the copse to never despawn.
corpse-time: 120

#Spawn a corpse when the player dies?
on-death: true

#Put the players items into a GUI when they die? Click the the corpse to open the GUI.
looting-inventory: true

#Should the corpse automaticly despawn after it has been looted? (Only has effect is looting-inventory is true!)
despawn-after-looted: true

#Show the username of the player? If you set this to false ' ' will be used for the username.
#The skin will still show even if you choose not do display the username.
show-tags: true

#This is used to specify what world(s) corpses should spawn when somebody dies.
#Set world to 'all' for every world.
#Use '|' to add multiple worlds.
world: all

#Title of inventory created when you click the corpses head to loot it. 
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 32 character limit on GUI lengths. If your title is more then that you will get a error on the console.
gui-title: "%corpse%'s Items"

#This is the username of the corpse.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
#Minecraft has a 16 character limit on name lengths. If your title is more then that you will get a error on the console.
username-format: "%corpse%"

#This is the message sent when you finish looting the corpse. Set the message to "none" to disable.
#%corpse% gets replaced with the corpses name.
#Color codes and unicode characters work, but might be glitchy.
finish-looting-message: "&bYou have finished looting %corpse%'s corpse."

#Due to a Minecraft quirk with how the corpses work, the hitboxes were not normal player hitboxes.
#I have now made it so a invisible Cows spawn that covers the whole corpse.
#When you click on the invisible Cow it does the same thing as clicking on the corpse.
#Set to false to use the old glitchy hitboxes.
new-hitboxes: false

#Should we render player armor and items on the corpses?
#Set to false to not render player armor and items on the corpses
render-armor: true

#Should we save corpses on restart?
#Note: v1_8_R1 and below will not save. (1.8.8+ will save)
save-corpses: true

#Should we send anonymous data to Eric?
#The only data sent to my web server is what Minecraft version and what type of server you're running.
#My goal with this data is to see which is the most popular version so I can improve this plugin as best as I can.
#I totally understand if you do not want to send my server data, hence why this option is here.
#The public static are located here if you wish to see them: http://web2.golde.org/files/spigot/CorpseReborn/stats/
send-data: true
`

**Comment by egold555** [comment]
I created a addon a while ago to do just this, One day I might add it into the actual plugi if enough people want this feature.

https://github.com/egold555/CorpseReborn-Add-ons/raw/master/Releases/CRNoItemsNoCorpse.jar
